# Generated by Django 2.0.5 on 2018-05-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodigester',
            name='volume',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
